/*
 * File: app/store/Customers.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ins.store.Customers', {
	extend: 'Ext.data.Store',
	
	model: 'Ins.model.Customer',
    pageSize: 15,
    autoLoad: true,
    proxy: {
    	type: 'ajax',
    	url: '/SimpleWorkflow/flow/customer/all',
    	method: 'GET',
    	reader: {
    		type: 'json',
    		totalProperty: 'totalCount',
    		root: 'data',
    		successProperty: 'success'
    	}
    }
});